# Generated by Django 3.0.5 on 2020-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainoperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
