# Generated by Django 3.0.1 on 2020-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainoperation', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
