# Generated by Django 3.0.5 on 2020-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainoperation', '0002_auto_20200422_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
