# Generated by Django 3.0.1 on 2020-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainoperation', '0003_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
